name: Continuous Integration

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Add steps for your specific language and framework
      # For example, for Node.js:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm' # Or 'yarn', 'pnpm'

      - name: Install Dependencies
        run: npm install

      - name: Run Unit & Integration Tests
        run: npm test # Assumes you have a 'test' script

      - name: Build Application
        run: npm run build # Assumes you have a 'build' script
