name: Continuous Integration

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  verify-project:
    name: Verify Project Integrity
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      # This step checks for syntax errors in your main server file without
      # starting the server. It's a fast and effective sanity check.
      - name: Check Server File Syntax
        run: node -c server.js # Or the path to your main application file
