name: Commit Message Lint

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  lint-commit-message:
    name: Lint Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        uses: amannn/action-semantic-pull-request@v5
        with:
          # You can configure the types (e.g., feat, fix, docs, style)
          types: |
            feat
            fix
            docs
            style
            refactor
            test
            chore
            revert
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
