name: Super-Linter

on:
  pull_request:
    branches:
      - main
      - develop
      - feature/*
      - hotfix/*

jobs:
  test:
      runs-on: unbutu-latest
      container:
        image: node:20
      steps:
        - uses: actions/checkout@v3
          with:
            node-version: 22
        - run: npm ci
        - run: npm test
        - run: npm run build
